services:
  - type: web
    name: chubby-properties
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    healthCheckPath: /
    autoDeploy: true
